# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-02-03 11:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_post_has_like'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='user_who_give_like',
            field=models.CharField(default='', max_length=255),
        ),
    ]
