# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-01-31 18:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0002_auto_20190131_1823'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='photo',
            field=models.ImageField(blank=True, upload_to='group_photos'),
        ),
    ]
