# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-02-04 17:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0005_auto_20190202_1923'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='group',
            options={'ordering': ('-created_at',), 'permissions': (('add_post', 'Can add post to group'), ('delete_post', 'Can delete post in group'), ('update_post', 'Can update post in group'))},
        ),
    ]
